# Generated by Django 5.0.1 on 2024-01-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_price_currency_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_currency",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
