# Generated by Django 5.0.1 on 2024-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_cartitem_cart_alter_cartitem_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="cart_items",
            field=models.ManyToManyField(related_name="orders", to="api.cartitem"),
        ),
    ]
